name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-classifier ./image_classifier
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-classifier

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy image-classifier \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-classifier \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project=${{ secrets.GCP_PROJECT_ID }}
